services:
  api:
    build: .
    restart: unless-stopped
    command: ["uv", "run", "uvicorn", "main:app", "--app-dir", "/home/app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    ports:
      - "${PORT}:8000"
    volumes:
      - .:/home
      - hf_cache:/root/.cache/huggingface
    env_file:
      - .env
    depends_on:
      - es
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.2.2
    container_name: es
    restart: unless-stopped
    environment:
      - node.name=es
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "${ES_PORT}:9200"
  kibana:
    image: docker.elastic.co/kibana/kibana:9.2.2
    container_name: kibana
    restart: unless-stopped
    ports:
      - "${KIBANA_PORT}:5601"
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=http://es:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
    depends_on:
      - es

volumes:
  hf_cache:
  es_data: